name: scratch_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_lints: ^2.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/success/
    - assets/images/shopping/
    - assets/images/profile/
    - assets/images/products/
    - assets/images/orders/
    - assets/images/icons/
    - assets/images/deals/
    - assets/images/cart/
    - assets/images/books/
    - assets/images/banners/
